[project]
name = "dcs-areas"
version = "0.1.0"
description = "A simple visualization of DCS maps, with some data about their sizes"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "simplestmaps>=1.7.0",
    "telluric>=0.15.0",
]
